use psa;

-- adicionando instituição 
INSERT INTO instituicao (Nome_Instituicao, Email, Telefone, Enderecos, Descricao) VALUES 
('Portal de Socorro e Apoio', 'portaldesocorro@gmail.com', '(11) 98765-4321', 'Rua dos Voluntários, 123 - Centro - CEP 12345-678', 'O Portal de Socorro e Apoio é uma instituição dedicada a fornecer assistência humanitária em situações de emergência e apoio comunitário. Nossa missão é ajudar aqueles que mais precisam em momentos difíceis, fornecendo recursos essenciais e apoio emocional.');

-- adicionando itens na tabela usuarios
INSERT INTO Usuarios (Nome_Usuarios, Email, Endereco, Tipo_de_Usuarios) VALUES 
('Maria', 'maria@gmail.com', 'Rua Roberto Michellin, 95 - Antônio Marincek - CEP 14061-190', 'Comum'),
('António', 'antonio@hotmail.com', 'Rua das Flores, 32 - São Paulo - CEP 01001-000', 'Comum'),
('João', 'joao@gmail.com', 'Avenida Paulista, 1234 - Bela Vista - CEP 01310-000', 'Comum'),
('José', 'jose@hotmail.com', 'Rua da Consolação, 123 - Consolação - CEP 01301-100', 'Comum'),
('Francisco', 'francisco@gmail.com', 'Rua Augusta, 1001 - Consolação - CEP 01304-001', 'Comum'),
('Ana', 'ana@hotmail.com', 'Rua Oscar Freire, 900 - Pinheiros - CEP 05409-001', 'Comum'),
('Manuel', 'manuel@gmail.com', 'Avenida Faria Lima, 2232 - Pinheiros - CEP 05489-001', 'Comum'),
('Luís', 'luis@hotmail.com', 'Rua Barão de Tatuí, 150 - Santa Cecília - CEP 01226-030', 'Comum'),
('Pedro', 'pedro@gmail.com', 'Rua Haddock Lobo, 595 - Cerqueira César - CEP 01414-001', 'Comum'),
('Mariana', 'mariana@hotmail.com', 'Avenida Brasil, 1200 - Jardim Paulista - CEP 01430-000', 'Comum'),
('Fernando', 'fernando@gmail.com', 'Rua Estados Unidos, 2100 - Jardim América - CEP 01427-002', 'Comum'),
('Margarida', 'margarida@hotmail.com', 'Alameda Santos, 231 - Cerqueira César - CEP 01418-000', 'Comum'),
('Isabel', 'isabel@gmail.com', 'Rua Augusta, 1137 - Consolação - CEP 01305-100', 'Comum'),
('Sofia', 'sofia@hotmail.com', 'Rua Haddock Lobo, 557 - Cerqueira César - CEP 01414-000', 'Comum'),
('Carlos', 'carlos@gmail.com', 'Rua Oscar Freire, 777 - Cerqueira César - CEP 01426-000', 'Comum'),
('Inês', 'ines@hotmail.com', 'Avenida Paulista, 1234 - Bela Vista - CEP 01310-000', 'Comum'),
('Helena', 'helena@gmail.com', 'Rua Augusta, 1001 - Consolação - CEP 01304-001', 'Comum'),
('Miguel', 'miguel@hotmail.com', 'Rua das Flores, 32 - São Paulo - CEP 01001-000', 'Comum'),
('Nuno', 'nuno@gmail.com', 'Avenida Faria Lima, 2232 - Pinheiros - CEP 05489-001', 'Comum'),
('Eduardo', 'eduardo@hotmail.com', 'Rua Barão de Tatuí, 150 - Santa Cecília - CEP 01226-030', 'Comum'),
('Amélia', 'amelia@gmail.com', 'Rua Haddock Lobo, 595 - Cerqueira César - CEP 01414-001', 'Comum'),
('Bernardo', 'bernardo@hotmail.com', 'Avenida Brasil, 1200 - Jardim Paulista - CEP 01430-000', 'Comum'),
('Catarina', 'catarina@gmail.com', 'Rua Estados Unidos, 2100 - Jardim América - CEP 01427-002', 'Comum'),
('Jaime', 'jaime@hotmail.com', 'Alameda Santos, 231 - Cerqueira César - CEP 01418-000', 'Comum'),
('Joana', 'joana@gmail.com', 'Rua Augusta, 1137 - Consolação - CEP 01305-100', 'Comum'),
('Rui', 'rui@hotmail.com', 'Rua Haddock Lobo, 557 - Cerqueira César - CEP 01414-000', 'Comum'),
('Alexandre', 'alexandre@gmail.com', 'Rua Oscar Freire, 777 - Cerqueira César - CEP 01426-000', 'Comum'),
('Domingos', 'domingos@hotmail.com', 'Avenida Paulista, 1234 - Bela Vista - CEP 01310-000', 'Comum'),
('Frederico', 'frederico@gmail.com', 'Rua Augusta, 1001 - Consolação - CEP 01304-001', 'Comum'),
('Jorge', 'jorge@hotmail.com', 'Rua das Flores, 32 - São Paulo - CEP 01001-000', 'Comum'),
('Josefa', 'josefa@gmail.com', 'Avenida Faria Lima, 2232 - Pinheiros - CEP 05489-001', 'Comum'),
('Teresa', 'teresa@hotmail.com', 'Rua Barão de Tatuí, 150 - Santa Cecília - CEP 01226-030', 'Comum'),
('Vasco', 'vasco@gmail.com', 'Rua Haddock Lobo, 595 - Cerqueira César - CEP 01414-001', 'Comum'),
('Alexandra', 'alexandra@hotmail.com', 'Avenida Brasil, 1200 - Jardim Paulista - CEP 01430-000', 'Comum'),
('Beatriz', 'beatriz@gmail.com', 'Rua Estados Unidos, 2100 - Jardim América - CEP 01427-002', 'Comum'),
('Daniel', 'daniel@hotmail.com', 'Alameda Santos, 231 - Cerqueira César - CEP 01418-000', 'Comum'),
('Duarte', 'duarte@gmail.com', 'Rua Augusta, 1137 - Consolação - CEP 01305-100', 'Comum'),
('Joaquim', 'joaquim@hotmail.com', 'Rua Haddock Lobo, 557 - Cerqueira César - CEP 01414-000', 'Comum'),
('Marta', 'marta@gmail.com', 'Rua Oscar Freire, 777 - Cerqueira César - CEP 01426-000', 'Comum'),
('Ricardo', 'ricardo@hotmail.com', 'Avenida Paulista, 1234 - Bela Vista - CEP 01310-000', 'Comum'),
('Rodrigo', 'rodrigo@gmail.com', 'Rua Augusta, 1001 - Consolação - CEP 01304-001', 'Comum'),
('Rosa', 'rosa@hotmail.com', 'Rua das Flores, 32 - São Paulo - CEP 01001-000', 'Comum'),
('Virgínia', 'virginia@gmail.com', 'Avenida Faria Lima, 2232 - Pinheiros - CEP 05489-001', 'Comum'),
('Armando', 'armando@hotmail.com', 'Rua Barão de Tatuí, 150 - Santa Cecília - CEP 01226-030', 'Comum'),
('Bárbara', 'barbara@gmail.com', 'Rua Haddock Lobo, 595 - Cerqueira César - CEP 01414-001', 'Comum'),
('Bento', 'bento@hotmail.com', 'Avenida Brasil, 1200 - Jardim Paulista - CEP 01430-000', 'Comum'),
('Carolina', 'carolina@gmail.com', 'Rua Estados Unidos, 2100 - Jardim América - CEP 01427-002', 'Comum'),
('Diogo', 'diogo@hotmail.com', 'Alameda Santos, 231 - Cerqueira César - CEP 01418-000', 'Comum'),
('Elias', 'elias@gmail.com', 'Rua Augusta, 1137 - Consolação - CEP 01305-100', 'Comum'),
('Jerónimo', 'jeronimo@hotmail.com', 'Rua Haddock Lobo, 557 - Cerqueira César - CEP 01414-000', 'Comum');

UPDATE usuarios SET ID_Instituicao = 1 WHERE ID_Usuarios BETWEEN 1 AND 58;

-- adicionando itens da tabela agua_potavel
INSERT INTO agua_potavel (Volume, Data_de_Validade, Nivel_de_Urgencia, Embalagem, Descricao, Fornecedor) VALUES 
(12.5, '2024-08-01', 2, 'Garrafa PET', 'Água mineral natural engarrafada', 'Kryspro'),
(15.2, '2024-07-25', 3, 'Galão', 'Água potável tratada com ozônio', 'Kryspal'),
(20.8, '2024-08-10', 1, 'Embalagem plástica', 'Água filtrada em embalagem prática', 'Krystech'),
(12.3, '2024-07-20', 2, 'Garrafa de vidro', 'Água purificada em garrafa de vidro reciclável', 'Krysmax'),
(18.6, '2024-07-30', 3, 'Garrafa PET', 'Água mineral natural com alto teor de cálcio', 'Krystrex'),
(11.2, '2024-07-15', 1, 'Embalagem plástica', 'Água mineral natural em embalagem prática', 'Perriérlux'),
(13.5, '2024-08-05', 2, 'Garrafa PET', 'Água mineral natural enriquecida com minerais', 'Perriérline'),
(16.9, '2024-07-22', 3, 'Galão', 'Água mineral natural proveniente de fonte pura', 'Perriérwave'),
(14.8, '2024-07-28', 1, 'Embalagem plástica', 'Água purificada em embalagem econômica', 'Perriérsoft'),
(17.3, '2024-08-08', 2, 'Garrafa de vidro', 'Água potável tratada com tecnologia avançada', 'Perriérlux'),
(19.5, '2024-07-18', 3, 'Garrafa de vidro', 'Água mineral natural em garrafa de vidro retornável', 'Perriérdeluxe'),
(22.1, '2024-07-27', 1, 'Embalagem plástica', 'Água filtrada em embalagem prática', 'São Lourênco'),
(15.7, '2024-08-03', 2, 'Galão', 'Água potável tratada com ozônio', 'São Loureço'),
(18.4, '2024-07-24', 3, 'Embalagem plástica', 'Água mineral natural em embalagem prática', 'São Lourenço'),
(20.6, '2024-08-12', 1, 'Garrafa PET', 'Água filtrada em embalagem prática', 'São Loureńço'),
(23.2, '2024-07-19', 2, 'Galão', 'Água potável tratada com ozônio', 'São Lourenço'),
(16.8, '2024-07-31', 3, 'Embalagem plástica', 'Água mineral natural em embalagem prática', 'São Lourencó'),
(19.4, '2024-08-06', 1, 'Garrafa de vidro', 'Água potável tratada com tecnologia avançada', 'Shin'),
(21.7, '2024-07-26', 2, 'Garrafa de vidro', 'Água mineral natural proveniente de fonte pura', 'Shiin'),
(24.5, '2024-08-02', 3, 'Garrafa PET', 'Água purificada em embalagem econômica', 'Shin'),
(18.3, '2024-08-09', 1, 'Galão', 'Água mineral natural com alto teor de cálcio', 'Shhinn'),
(21.6, '2024-07-17', 2, 'Embalagem plástica', 'Água filtrada em embalagem prática', 'Shinpro'),
(25.1, '2024-07-23', 3, 'Garrafa de vidro', 'Água purificada em garrafa de vidro retornável', 'Shhinmax'),
(27.3, '2024-08-11', 1, 'Garrafa PET', 'Água potável tratada com ozônio', 'Kryssper'),
(29.8, '2024-08-07', 2, 'Garrafa de vidro', 'Água mineral natural proveniente de fonte pura', 'Kryshin'),
(33.2, '2024-07-29', 3, 'Galão', 'Água potável tratada com tecnologia avançada', 'Krystinn'),
(35.7, '2024-08-04', 1, 'Garrafa PET', 'Água mineral natural com alto teor de cálcio', 'Krysin'),
(38.4, '2024-07-21', 2, 'Galão', 'Água potável tratada com ozônio', 'Krysul'),
(41.5, '2024-07-16', 3, 'Embalagem plástica', 'Água filtrada em embalagem prática', 'Kryspira'),
(44.2, '2024-08-13', 1, 'Garrafa de vidro', 'Água mineral natural enriquecida com minerais', 'Perriérmax'),
(47.6, '2024-07-14', 2, 'Garrafa de vidro', 'Água potável tratada com tecnologia avançada', 'Perriérpro'),
(50.8, '2024-08-14', 3, 'Galão', 'Água mineral natural em embalagem prática', 'Perriérline'),
(54.3, '2024-07-13', 1, 'Embalagem plástica', 'Água purificada em embalagem econômica', 'Perriérsoft'),
(58.2, '2024-08-15', 2, 'Galão', 'Água potável tratada com ozônio', 'Perriérwave'),
(62.1, '2024-07-12', 3, 'Garrafa de vidro', 'Água mineral natural proveniente de fonte pura', 'Perriérflare'),
(65.7, '2024-08-16', 1, 'Garrafa PET', 'Água mineral natural em embalagem prática', 'Perriérnova'),
(68.9, '2024-07-11', 2, 'Embalagem plástica', 'Água filtrada em embalagem prática', 'Perriérwave'),
(72.5, '2024-08-17', 3, 'Galão', 'Água potável tratada com ozônio', 'Perriérlux'),
(75.4, '2024-07-10', 1, 'Garrafa de vidro', 'Água mineral natural enriquecida com minerais', 'Perriérmax'),
(78.6, '2024-08-18', 2, 'Garrafa PET', 'Água purificada em embalagem econômica', 'Perriérpro'),
(82.3, '2024-07-09', 3, 'Galão', 'Água potável tratada com tecnologia avançada', 'Perriérline'),
(85.7, '2024-08-19', 1, 'Embalagem plástica', 'Água filtrada em embalagem prática', 'Perriérsoft'),
(89.5, '2024-07-08', 2, 'Garrafa de vidro', 'Água mineral natural proveniente de fonte pura', 'Perriérwave'),
(92.6, '2024-08-20', 3, 'Galão', 'Água potável tratada com ozônio', 'Perriérnova'),
(96.2, '2024-07-07', 1, 'Garrafa PET', 'Água mineral natural em embalagem prática', 'Perriérnova'),
(99.5, '2024-08-21', 2, 'Embalagem plástica', 'Água purificada em embalagem econômica', 'Perriérwave'),
(102.8, '2024-07-06', 3, 'Galão', 'Água potável tratada com tecnologia avançada', 'Perriérlux');

-- adicionado itens a tabela alimentos
INSERT INTO alimentos (Nome, Categoria, Data_de_Validade, Quantidade, Descricao, Nivel_de_Urgencia, Fornecedor) VALUES 
('Arroz', 'Grãos', '2025-12-31', 20.0, 'Arroz branco de qualidade premium, embalado a vácuo para garantir frescor prolongado.', 1, 'Arroz Delícia'),
('Feijão', 'Leguminosas', '2025-12-31', 15.0, 'Feijão carioca selecionado, embalado hermeticamente para manter sua qualidade.', 2, 'Feijão Top'),
('Macarrão', 'Massas', '2025-12-31', 25.0, 'Macarrão tipo espaguete de trigo durum, embalado em pacotes individuais para facilitar o armazenamento.', 3, 'Massas Reunidas'),
('Farinha de trigo', 'Farináceos', '2025-12-31', 30.0, 'Farinha de trigo especial, ideal para preparo de pães e massas.', 1, 'Moinho Feliz'),
('Óleo de soja', 'Óleos e gorduras', '2025-12-31', 18.0, 'Óleo de soja refinado, fonte de ácidos graxos essenciais.', 2, 'Óleos do Vale'),
('Açúcar', 'Açúcares e adoçantes', '2025-12-31', 22.0, 'Açúcar cristal branco, ideal para uso doméstico e industrial.', 3, 'Açúcares Finos'),
('Sal refinado', 'Temperos e condimentos', '2025-12-31', 17.0, 'Sal refinado de alta pureza, adequado para uso culinário.', 1, 'Sal Marinho'),
('Café em pó', 'Café e chá', '2025-12-31', 21.0, 'Café em pó torrado e moído, saboroso e encorpado.', 2, 'Café Bom Dia'),
('Leite em pó', 'Laticínios', '2025-12-31', 19.0, 'Leite em pó integral, fonte de cálcio e vitaminas.', 3, 'Laticínios do Sítio'),
('Fermento em pó', 'Farináceos', '2025-12-31', 16.0, 'Fermento em pó químico, utilizado para dar crescimento a massas.', 1, 'Fermento Vivo'),
('Fubá', 'Farináceos', '2025-12-31', 14.0, 'Fubá de milho de alta qualidade, ideal para preparo de polenta e bolos.', 2, 'Fubá Feliz'),
('Creme de leite', 'Laticínios', '2025-12-31', 20.0, 'Creme de leite fresco, perfeito para preparo de molhos e sobremesas.', 3, 'Cremoso da Fazenda'),
('Creme de cebola em pó', 'Temperos e condimentos', '2025-12-31', 18.0, 'Tempero em pó à base de cebola, para dar sabor especial a pratos.', 1, 'Cebola Dourada'),
('Extrato de tomate', 'Temperos e condimentos', '2025-12-31', 25.0, 'Extrato de tomate concentrado, essencial para preparo de molhos.', 2, 'Tomate Fresco'),
('Gelatina', 'Doces e sobremesas', '2025-12-31', 23.0, 'Gelatina em pó, saborosa e fácil de preparar.', 3, 'Gelatinas Saborosas'),
('Molho de tomate', 'Temperos e condimentos', '2025-12-31', 16.0, 'Molho de tomate pronto para uso, com ingredientes selecionados.', 1, 'Molho Bom'),
('Vinagre de maçã', 'Temperos e condimentos', '2025-12-31', 20.0, 'Vinagre de maçã natural, ideal para temperar saladas e conservar alimentos.', 2, 'Vinagre da Fazenda'),
('Biscoito de maisena', 'Biscoitos e salgadinhos', '2025-12-31', 19.0, 'Biscoito de maisena crocante e saboroso, ótimo para acompanhar o café.', 3, 'Biscoitos da Vovó'),
('Achocolatado em pó', 'Café e chá', '2025-12-31', 22.0, 'Achocolatado em pó solúvel, fonte de cálcio e energia.', 1, 'Chocolatado Gostoso'),
('Geleia de morango', 'Doces e sobremesas', '2025-12-31', 18.0, 'Geleia de morango artesanal, feita com frutas frescas.', 2, 'Morangos da Fazenda'),
('Polpa de frutas', 'Frutas', '2025-12-31', 21.0, 'Polpa de frutas congelada, prática e versátil para preparo de sucos e sobremesas.', 3, 'Polpas Naturais'),
('Farofa pronta', 'Farináceos', '2025-12-31', 16.0, 'Farofa pronta temperada, ideal para acompanhar churrascos e feijoadas.', 1, 'Farofa Fácil'),
('Catchup', 'Temperos e condimentos', '2025-12-31', 20.0, 'Catchup de tomate, com sabor suave e consistência cremosa.', 2, 'Tomate da Roça'),
('Mostarda', 'Temperos e condimentos', '2025-12-31', 23.0, 'Mostarda amarela suave, perfeita para sanduíches e petiscos.', 3, 'Mostarda da Vovó'),
('Milho verde em conserva', 'Enlatados e conservas', '2025-12-31', 18.0, 'Milho verde em conserva, pronto para consumo.', 1, 'Milho Dourado'),
('Ervilha em conserva', 'Enlatados e conservas', '2025-12-31', 22.0, 'Ervilha em conserva, selecionada e embalada cuidadosamente.', 2, 'Ervilha Fresca'),
('Atum enlatado', 'Enlatados e conservas', '2025-12-31', 20.0, 'Atum em conserva, fonte de proteína e ômega-3.', 3, 'Atum do Mar'),
('Sardinha em lata', 'Enlatados e conservas', '2025-12-31', 25.0, 'Sardinha em lata, rica em nutrientes e saborosa.', 1, 'Sardinha Feliz'),
('Doce de leite', 'Doces e sobremesas', '2025-12-31', 17.0, 'Doce de leite tradicional, cremoso e irresistível.', 2, 'Doces da Fazenda'),
('Leite condensado', 'Laticínios', '2025-12-31', 23.0, 'Leite condensado cremoso, ideal para preparo de sobremesas.', 3, 'Leites Especiais'),
('Molho shoyu', 'Temperos e condimentos', '2025-12-31', 19.0, 'Molho shoyu tradicional, para dar um toque oriental aos pratos.', 1, 'Shoyu da Terra'),
('Creme de avelã', 'Doces e sobremesas', '2025-12-31', 22.0, 'Creme de avelã com chocolate, perfeito para passar no pão.', 2, 'Cremoso de Nutella'),
('Goiabada', 'Doces e sobremesas', '2025-12-31', 20.0, 'Goiabada cascão, produzida com goiabas selecionadas.', 3, 'Goiabada Real'),
('Bolacha recheada', 'Biscoitos e salgadinhos', '2025-12-31', 17.0, 'Bolacha recheada sabor chocolate, ideal para lanches rápidos.', 1, 'Bolachas Reunidas'),
('Cereal matinal', 'Cereais', '2025-12-31', 23.0, 'Cereal matinal rico em fibras e vitaminas, para um café da manhã saudável.', 2, 'Cereal da Manhã'),
('Geléia real', 'Doces e sobremesas', '2025-12-31', 21.0, 'Geléia real pura, rica em nutrientes e energia.', 3, 'Rainha das Abelhas'),
('Pão de forma', 'Bolos, pães e massas', '2025-12-31', 20.0, 'Pão de forma integral, fonte de fibras e nutrientes.', 1, 'Pães da Hora'),
('Chocolate em pó', 'Café e chá', '2025-12-31', 24.0, 'Chocolate em pó solúvel, para preparo de bebidas quentes e sobremesas.', 2, 'Chocolate da Fazenda'),
('Doce de figo', 'Doces e sobremesas', '2025-12-31', 19.0, 'Doce de figo em calda, produzido de forma artesanal.', 3, 'Figo Dourado'),
('Polenta instantânea', 'Farináceos', '2025-12-31', 18.0, 'Polenta instantânea pré-cozida, prática e versátil.', 1, 'Polenta Fácil'),
('Biscoito de polvilho', 'Biscoitos e salgadinhos', '2025-12-31', 22.0, 'Biscoito de polvilho assado, leve e crocante.', 2, 'Biscoitos da Fazenda'),
('Chá verde', 'Café e chá', '2025-12-31', 20.0, 'Chá verde natural, antioxidante e revigorante.', 3, 'Chá da Montanha'),
('Suco em pó', 'Bebidas', '2025-12-31', 23.0, 'Suco em pó sabor laranja, fácil de preparar e refrescante.', 1, 'Sucos da Fazenda'),
('Azeitonas em conserva', 'Enlatados e conservas', '2025-12-31', 19.0, 'Azeitonas verdes em conserva, perfeitas para petiscos e saladas.', 2, 'Azeitonas do Sítio'),
('Molho barbecue', 'Temperos e condimentos', '2025-12-31', 17.0, 'Molho barbecue defumado, ideal para carnes e sanduíches.', 3, 'BBQ Master'),
('Pasta de amendoim', 'Doces e sobremesas', '2025-12-31', 22.0, 'Pasta de amendoim natural, fonte de proteínas e energia.', 1, 'Amendoim da Fazenda'),
('Arroz', 'Grãos', '2025-12-31', 20.0, 'Arroz branco de qualidade superior, proveniente de lavouras selecionadas.', 1, 'Arroz Delícia'),
('Feijão', 'Leguminosas', '2025-12-31', 15.0, 'Feijão carioca de primeira qualidade, pronto para o cozimento.', 2, 'Feijão Top'),
('Macarrão', 'Massas', '2025-12-31', 25.0, 'Macarrão tipo espaguete de trigo durum, produzido artesanalmente.', 3, 'Massas Reunidas'),
('Farinha de trigo', 'Farináceos', '2025-12-31', 30.0, 'Farinha de trigo especial, ideal para pães e bolos.', 1, 'Moinho Feliz'),
('Óleo de soja', 'Óleos e gorduras', '2025-12-31', 18.0, 'Óleo de soja puro, prensado a frio para manter suas propriedades.', 2, 'Óleos do Vale'),
('Açúcar', 'Açúcares e adoçantes', '2025-12-31', 22.0, 'Açúcar cristal refinado, adoça sem deixar resíduos.', 3, 'Açúcares Finos'),
('Sal refinado', 'Temperos e condimentos', '2025-12-31', 17.0, 'Sal refinado iodado, indispensável na culinária.', 1, 'Sal Marinho'),
('Café em pó', 'Café e chá', '2025-12-31', 21.0, 'Café em pó torrado e moído na hora, aroma irresistível.', 2, 'Café Bom Dia'),
('Leite em pó', 'Laticínios', '2025-12-31', 19.0, 'Leite em pó integral, obtido a partir de leite fresco.', 3, 'Laticínios do Sítio'),
('Fermento em pó', 'Farináceos', '2025-12-31', 16.0, 'Fermento em pó químico, essencial para pães e bolos.', 1, 'Fermento Vivo'),
('Fubá', 'Farináceos', '2025-12-31', 14.0, 'Fubá de milho de excelente qualidade, sem aditivos.', 2, 'Fubá Feliz'),
('Creme de leite', 'Laticínios', '2025-12-31', 20.0, 'Creme de leite fresco, sem conservantes.', 3, 'Cremoso da Fazenda'),
('Creme de cebola em pó', 'Temperos e condimentos', '2025-12-31', 18.0, 'Creme de cebola em pó, para realçar o sabor dos pratos.', 1, 'Cebola Dourada'),
('Extrato de tomate', 'Temperos e condimentos', '2025-12-31', 25.0, 'Extrato de tomate concentrado, sem adição de água.', 2, 'Tomate Fresco'),
('Gelatina', 'Doces e sobremesas', '2025-12-31', 23.0, 'Gelatina em pó sabor frutas, colorida e saborosa.', 3, 'Gelatinas Saborosas'),
('Molho de tomate', 'Temperos e condimentos', '2025-12-31', 16.0, 'Molho de tomate caseiro, feito com tomates frescos.', 1, 'Molho Bom'),
('Vinagre de maçã', 'Temperos e condimentos', '2025-12-31', 20.0, 'Vinagre de maçã natural, fermentado de forma tradicional.', 2, 'Vinagre da Fazenda'),
('Biscoito de maisena', 'Biscoitos e salgadinhos', '2025-12-31', 19.0, 'Biscoito de maisena crocante, irresistível para o lanche.', 3, 'Biscoitos da Vovó'),
('Achocolatado em pó', 'Café e chá', '2025-12-31', 17.0, 'Achocolatado em pó solúvel, fonte de cálcio e energia.', 1, 'Chocolatado Gostoso'),
('Geleia de morango', 'Doces e sobremesas', '2025-12-31', 18.0, 'Geleia de morango artesanal, feita com frutas frescas.', 2, 'Morangos da Fazenda'),
('Polpa de frutas', 'Frutas', '2025-12-31', 21.0, 'Polpa de frutas congelada, prática e versátil para preparo de sucos e sobremesas.', 3, 'Polpas Naturais'),
('Farofa pronta', 'Farináceos', '2025-12-31', 16.0, 'Farofa pronta temperada, ideal para acompanhar churrascos e feijoadas.', 1, 'Farofa Fácil'),
('Catchup', 'Temperos e condimentos', '2025-12-31', 20.0, 'Catchup de tomate, com sabor suave e consistência cremosa.', 2, 'Tomate da Roça'),
('Mostarda', 'Temperos e condimentos', '2025-12-31', 23.0, 'Mostarda amarela suave, perfeita para sanduíches e petiscos.', 3, 'Mostarda da Vovó'),
('Milho verde em conserva', 'Enlatados e conservas', '2025-12-31', 18.0, 'Milho verde em conserva, pronto para consumo.', 1, 'Milho Dourado'),
('Ervilha em conserva', 'Enlatados e conservas', '2025-12-31', 22.0, 'Ervilha em conserva, selecionada e embalada cuidadosamente.', 2, 'Ervilha Fresca'),
('Atum enlatado', 'Enlatados e conservas', '2025-12-31', 20.0, 'Atum em conserva, fonte de proteína e ômega-3.', 3, 'Atum do Mar'),
('Sardinha em lata', 'Enlatados e conservas', '2025-12-31', 25.0, 'Sardinha em lata, rica em nutrientes e saborosa.', 1, 'Sardinha Feliz'),
('Doce de leite', 'Doces e sobremesas', '2025-12-31', 17.0, 'Doce de leite tradicional, cremoso e irresistível.', 2, 'Doces da Fazenda'),
('Leite condensado', 'Laticínios', '2025-12-31', 23.0, 'Leite condensado cremoso, ideal para preparo de sobremesas.', 3, 'Leites Especiais'),
('Molho shoyu', 'Temperos e condimentos', '2025-12-31', 19.0, 'Molho shoyu tradicional, para dar um toque oriental aos pratos.', 1, 'Shoyu da Terra'),
('Creme de avelã', 'Doces e sobremesas', '2025-12-31', 22.0, 'Creme de avelã com chocolate, perfeito para passar no pão.', 2, 'Cremoso de Nutella'),
('Goiabada', 'Doces e sobremesas', '2025-12-31', 20.0, 'Goiabada cascão, produzida com goiabas selecionadas.', 3, 'Goiabada Real'),
('Bolacha recheada', 'Biscoitos e salgadinhos', '2025-12-31', 17.0, 'Bolacha recheada sabor chocolate, ideal para lanches rápidos.', 1, 'Bolachas Reunidas'),
('Cereal matinal', 'Cereais', '2025-12-31', 23.0, 'Cereal matinal rico em fibras e vitaminas, para um café da manhã saudável.', 2, 'Cereal da Manhã'),
('Geléia real', 'Doces e sobremesas', '2025-12-31', 21.0, 'Geléia real pura, rica em nutrientes e energia.', 3, 'Rainha das Abelhas'),
('Pão de forma', 'Bolos, pães e massas', '2025-12-31', 20.0, 'Pão de forma integral, fonte de fibras e nutrientes.', 1, 'Pães da Hora'),
('Chocolate em pó', 'Café e chá', '2025-12-31', 24.0, 'Chocolate em pó solúvel, para preparo de bebidas quentes e sobremesas.', 2, 'Chocolate da Fazenda'),
('Doce de figo', 'Doces e sobremesas', '2025-12-31', 19.0, 'Doce de figo em calda, produzido de forma artesanal.', 3, 'Figo Dourado'),
('Polenta instantânea', 'Farináceos', '2025-12-31', 18.0, 'Polenta instantânea pré-cozida, prática e versátil.', 1, 'Polenta Fácil'),
('Biscoito de polvilho', 'Biscoitos e salgadinhos', '2025-12-31', 22.0, 'Biscoito de polvilho assado, leve e crocante.', 2, 'Biscoitos da Fazenda'),
('Chá verde', 'Café e chá', '2025-12-31', 20.0, 'Chá verde natural, antioxidante e revigorante.', 3, 'Chá da Montanha'),
('Suco em pó', 'Bebidas', '2025-12-31', 23.0, 'Suco em pó sabor laranja, fácil de preparar e refrescante.', 1, 'Sucos da Fazenda'),
('Azeitonas em conserva', 'Enlatados e conservas', '2025-12-31', 19.0, 'Azeitonas verdes em conserva, perfeitas para petiscos e saladas.', 2, 'Azeitonas do Sítio'),
('Molho barbecue', 'Temperos e condimentos', '2025-12-31', 17.0, 'Molho barbecue defumado, ideal para carnes e sanduíches.', 3, 'BBQ Master'),
('Pasta de amendoim', 'Doces e sobremesas', '2025-12-31', 22.0, 'Pasta de amendoim natural, fonte de proteínas e energia.', 1, 'Amendoim da Fazenda'),
('Macarrão integral', 'Massas', '2025-12-31', 20.0, 'Macarrão integral de trigo orgânico, fonte de fibras e nutrientes.', 1, 'Massas Naturais'),
('Feijão preto', 'Leguminosas', '2025-12-31', 15.0, 'Feijão preto de qualidade superior, pronto para o cozimento.', 2, 'Feijão Premium'),
('Arroz integral', 'Grãos', '2025-12-31', 25.0, 'Arroz integral orgânico, rico em fibras e nutrientes essenciais.', 3, 'Arroz Natural'),
('Farinha de mandioca', 'Farináceos', '2025-12-31', 30.0, 'Farinha de mandioca torrada, para preparo de bijus e farofas.', 1, 'Mandioca Pura'),
('Óleo de milho', 'Óleos e gorduras', '2025-12-31', 18.0, 'Óleo de milho puro, prensado a frio para manter suas propriedades.', 2, 'Óleos da Terra'),
('Adoçante em pó', 'Açúcares e adoçantes', '2025-12-31', 22.0, 'Adoçante em pó dietético, adoça sem adicionar calorias.', 3, 'Adoçantes Zero'),
('Sal grosso', 'Temperos e condimentos', '2025-12-31', 17.0, 'Sal grosso marinho, para moer na hora e realçar o sabor dos pratos.', 1, 'Sal do Mar'),
('Café solúvel', 'Café e chá', '2025-12-31', 21.0, 'Café solúvel instantâneo, para preparo rápido e prático.', 2, 'Café Rápido'),
('Leite de coco em pó', 'Laticínios', '2025-12-31', 19.0, 'Leite de coco em pó, natural e sem aditivos artificiais.', 3, 'Coco Dourado'),
('Fermento biológico seco', 'Farináceos', '2025-12-31', 16.0, 'Fermento biológico seco, para massas de pães e pizzas.', 1, 'Fermento Vivo'),
('Fubá mimoso', 'Farináceos', '2025-12-31', 14.0, 'Fubá mimoso de alta qualidade, para polentas e bolos.', 2, 'Fubá Fino'),
('Creme de leite light', 'Laticínios', '2025-12-31', 20.0, 'Creme de leite light, com redução de gorduras e calorias.', 3, 'Cremoso Leve'),
('Creme de cebola em pó light', 'Temperos e condimentos', '2025-12-31', 18.0, 'Creme de cebola em pó light, para pratos saudáveis.', 1, 'Cebola Leve'),
('Extrato de tomate orgânico', 'Temperos e condimentos', '2025-12-31', 25.0, 'Extrato de tomate orgânico, cultivado sem agrotóxicos.', 2, 'Tomate Orgânico'),
('Gelatina diet', 'Doces e sobremesas', '2025-12-31', 23.0, 'Gelatina diet sabor frutas, sem adição de açúcares.', 3, 'Gelatinas Leves'),
('Molho de tomate caseiro', 'Temperos e condimentos', '2025-12-31', 16.0, 'Molho de tomate caseiro, feito com tomates frescos.', 1, 'Molho da Casa'),
('Vinagre de vinho tinto', 'Temperos e condimentos', '2025-12-31', 20.0, 'Vinagre de vinho tinto, envelhecido em barris de carvalho.', 2, 'Vinagre Fino'),
('Biscoito integral', 'Biscoitos e salgadinhos', '2025-12-31', 19.0, 'Biscoito integral de aveia, fonte de fibras e energia.', 3, 'Biscoitos Naturais'),
('Achocolatado diet', 'Café e chá', '2025-12-31', 17.0, 'Achocolatado diet, sem adição de açúcares, para uma dieta equilibrada.', 1, 'Chocolatado Light'),
('Geleia diet', 'Doces e sobremesas', '2025-12-31', 18.0, 'Geleia diet sabor frutas, sem adição de açúcares.', 2, 'Geleia Light'),
('Polpa de frutas orgânicas', 'Frutas', '2025-12-31', 21.0, 'Polpa de frutas orgânicas, sem conservantes ou corantes.', 3, 'Polpas Orgânicas'),
('Farofa pronta light', 'Farináceos', '2025-12-31', 16.0, 'Farofa pronta light, temperada e com redução de calorias.', 1, 'Farofa Leve'),
('Catchup diet', 'Temperos e condimentos', '2025-12-31', 20.0, 'Catchup diet, sem adição de açúcares, para uma alimentação saudável.', 2, 'Tomate Light'),
('Mostarda light', 'Temperos e condimentos', '2025-12-31', 23.0, 'Mostarda light, com redução de calorias e sabor marcante.', 3, 'Mostarda Suave'),
('Milho verde orgânico', 'Enlatados e conservas', '2025-12-31', 18.0, 'Milho verde orgânico em conserva, sem agrotóxicos.', 1, 'Milho Natural'),
('Ervilha orgânica em conserva', 'Enlatados e conservas', '2025-12-31', 22.0, 'Ervilha orgânica em conserva, cultivada de forma sustentável.', 2, 'Ervilha Bio'),
('Atum orgânico em lata', 'Enlatados e conservas', '2025-12-31', 20.0, 'Atum orgânico em lata, pescado de maneira responsável.', 3, 'Atum Eco'),
('Sardinha orgânica em lata', 'Enlatados e conservas', '2025-12-31', 25.0, 'Sardinha orgânica em lata, proveniente de pescas sustentáveis.', 1, 'Sardinha Bio'),
('Doce de leite diet', 'Doces e sobremesas', '2025-12-31', 17.0, 'Doce de leite diet, sem adição de açúcares, para dietas restritivas.', 2, 'Doce Light'),
('Leite condensado light', 'Laticínios', '2025-12-31', 23.0, 'Leite condensado light, com redução de gorduras e calorias.', 3, 'Leite Magro'),
('Molho shoyu light', 'Temperos e condimentos', '2025-12-31', 19.0, 'Molho shoyu light, com redução de sódio e calorias.', 1, 'Shoyu Suave'),
('Creme de avelã light', 'Doces e sobremesas', '2025-12-31', 22.0, 'Creme de avelã light, com redução de gorduras e calorias.', 2, 'Cremoso Light'),
('Goiabada diet', 'Doces e sobremesas', '2025-12-31', 20.0, 'Goiabada diet, sem adição de açúcares, para dietas com restrição de carboidratos.', 3, 'Goiabada Zero'),
('Bolacha recheada diet', 'Biscoitos e salgadinhos', '2025-12-31', 17.0, 'Bolacha recheada diet, sem adição de açúcares, para lanches equilibrados.', 1, 'Bolachas Light'),
('Cereal matinal diet', 'Cereais', '2025-12-31', 23.0, 'Cereal matinal diet, sem adição de açúcares, para um café da manhã saudável.', 2, 'Cereal Light'),
('Geléia real light', 'Doces e sobremesas', '2025-12-31', 21.0, 'Geléia real light, com redução de calorias e preservação dos nutrientes.', 3, 'Geléia Light'),
('Pão de forma integral', 'Bolos, pães e massas', '2025-12-31', 20.0, 'Pão de forma integral, rico em fibras e nutrientes essenciais.', 1, 'Pães Integrais'),
('Chocolate em pó light', 'Café e chá', '2025-12-31', 24.0, 'Chocolate em pó light, com redução de açúcares e menos calorias.', 2, 'Chocolate Diet'),
('Doce de figo diet', 'Doces e sobremesas', '2025-12-31', 19.0, 'Doce de figo diet, sem adição de açúcares, para sobremesas mais leves.', 3, 'Figo Light'),
('Polenta instantânea light', 'Farináceos', '2025-12-31', 18.0, 'Polenta instantânea light, com redução de calorias e menos gorduras.', 1, 'Polenta Fit'),
('Biscoito de polvilho light', 'Biscoitos e salgadinhos', '2025-12-31', 22.0, 'Biscoito de polvilho light, assado e menos calórico.', 2, 'Biscoitos Leves'),
('Chá verde diet', 'Café e chá', '2025-12-31', 20.0, 'Chá verde diet, sem adição de açúcares, para uma bebida mais saudável.', 3, 'Chá Verde Light'),
('Suco em pó light', 'Bebidas', '2025-12-31', 23.0, 'Suco em pó light sabor laranja, com redução de açúcares e menos calorias.', 1, 'Suco Light'),
('Azeitonas em conserva light', 'Enlatados e conservas', '2025-12-31', 17.0, 'Azeitonas em conserva light, menos gorduras e menos calorias.', 2, 'Azeitonas Leves'),
('Champignon em conserva light', 'Enlatados e conservas', '2025-12-31', 21.0, 'Champignon em conserva light, menos calorias e menos sódio.', 3, 'Champignons Leves'),
('Geleia de morango diet', 'Doces e sobremesas', '2025-12-31', 19.0, 'Geleia de morango diet, sem adição de açúcares, para sobremesas mais leves.', 1, 'Morango Zero'),
('Maionese light', 'Óleos e gorduras', '2025-12-31', 20.0, 'Maionese light, com menos gorduras e menos calorias.', 2, 'Maionese Suave'),
('Pão de mel light', 'Doces e sobremesas', '2025-12-31', 22.0, 'Pão de mel light, com menos açúcares e menos calorias.', 3, 'Pão Light'),
('Leite de soja em pó light', 'Bebidas', '2025-12-31', 18.0, 'Leite de soja em pó light, sem lactose e menos gorduras.', 1, 'Soja Light'),
('Margarina light', 'Óleos e gorduras', '2025-12-31', 23.0, 'Margarina light, com menos gorduras saturadas e menos calorias.', 2, 'Margarina Suave'),
('Mel diet', 'Açúcares e adoçantes', '2025-12-31', 19.0, 'Mel diet, sem adição de açúcares, para adoçar de forma saudável.', 3, 'Mel Zero'),
('Sagu light', 'Cereais', '2025-12-31', 21.0, 'Sagu light, preparado com menos açúcares e menos calorias.', 1, 'Sagu Suave'),
('Suco de uva integral', 'Bebidas', '2025-12-31', 24.0, 'Suco de uva integral, sem adição de açúcares, rico em antioxidantes.', 2, 'Uva Pura'),
('Vinho tinto seco', 'Bebidas', '2025-12-31', 18.0, 'Vinho tinto seco, de qualidade premium e sabor marcante.', 3, 'Vinho Nobre'),
('Catchup light', 'Temperos e condimentos', '2025-12-31', 20.0, 'Catchup light, sem adição de açúcares e menos calorias.', 1, 'Catchup Fit'),
('Mostarda diet', 'Temperos e condimentos', '2025-12-31', 23.0, 'Mostarda diet, sem adição de açúcares, para uma alimentação mais leve.', 2, 'Mostarda Zero'),
('Patê de atum light', 'Enlatados e conservas', '2025-12-31', 22.0, 'Patê de atum light, com menos gorduras e menos calorias.', 3, 'Atum Leve'),
('Requeijão light', 'Laticínios', '2025-12-31', 19.0, 'Requeijão light, com menos gorduras e menos calorias.', 1, 'Requeijão Suave'),
('Goiabada diet', 'Doces e sobremesas', '2025-12-31', 23.0, 'Goiabada diet, sem adição de açúcares, para sobremesas mais leves.', 2, 'Goiabada Zero'),
('Leite em pó desnatado', 'Laticínios', '2025-12-31', 20.0, 'Leite em pó desnatado, sem lactose e menos gorduras.', 3, 'Leite Desnatado'),
('Creme de avelã diet', 'Doces e sobremesas', '2025-12-31', 18.0, 'Creme de avelã diet, sem adição de açúcares, para dietas restritivas.', 1, 'Avelã Zero'),
('Sal light', 'Temperos e condimentos', '2025-12-31', 22.0, 'Sal light, com menos sódio e menos calorias.', 2, 'Sal Suave'),
('Chá mate diet', 'Café e chá', '2025-12-31', 23.0, 'Chá mate diet, sem adição de açúcares, para uma bebida mais saudável.', 3, 'Chá Mate Zero'),
('Fubá de milho', 'Farináceos', '2025-12-31', 17.0, 'Fubá de milho, para preparo de polentas e bolos.', 1, 'Fubá Fresco');

-- adicioando itens na tabela moveis_e_eletrodomesticos
INSERT INTO moveis_e_eletrodomesticos (Tipo_de_item, Marca, Modelo, Estado_de_Conservacao, Descricao) VALUES
('Sofá', 'SofáMaster', 'Luxo 2000', 'Novo', 'Sofá de couro legítimo, cor preta, com 3 lugares e apoios de braço.'),
('Mesa de Jantar', 'TopMóveis', 'Elegância Plus', 'Semi-novo', 'Mesa de jantar retangular, madeira de lei, com capacidade para 8 pessoas.'),
('Geladeira', 'FrioBom', 'GelaTop 5000', 'Usado', 'Geladeira frost-free, branca, com dispenser de água e sistema de economia de energia.'),
('Cama de Casal', 'DormeBem', 'ReiConforto', 'Novo', 'Cama de casal king-size, estrutura de metal resistente, colchão de molas ensacadas.'),
('Fogão', 'CulináriaMaster', 'Chef 8000', 'Semi-novo', 'Fogão a gás de 5 bocas, inox, com forno autolimpante e acendimento automático.'),
('TV', 'VisãoPerfeita', 'UltraHD 65"', 'Usado', 'Smart TV 4K, tela de 65 polegadas, conexão Wi-Fi, compatível com streaming.'),
('Guarda-Roupa', 'OrganizaTudo', 'SpaceMax', 'Novo', 'Guarda-roupa de 6 portas e 8 gavetas, cor branca, com espelho na porta central.'),
('Máquina de Lavar', 'LavaFácil', 'CleanPro 10kg', 'Semi-novo', 'Máquina de lavar roupa de 10kg, branca, com diversos programas de lavagem.'),
('Poltrona', 'ConfortoDesign', 'ErgoComfort', 'Novo', 'Poltrona reclinável, estofada em tecido suede, cor bege, com apoio para os pés.'),
('Micro-ondas', 'RapidHeat', 'QuickChef 30L', 'Usado', 'Micro-ondas com grill, capacidade de 30 litros, inox, diversas funções de cozimento.'),
('Cômoda', 'OrganizaTudo', 'CompactMax', 'Semi-novo', 'Cômoda com 5 gavetas e 2 portas, cor mogno, ideal para organizar roupas e acessórios.'),
('Aspirador de Pó', 'LimpezaMaster', 'PowerClean 2000', 'Usado', 'Aspirador de pó com potência de 2000W, filtro HEPA, ideal para alérgicos.'),
('Escrivaninha', 'EstudoTop', 'DeskMaster', 'Novo', 'Escrivaninha com 3 gavetas e espaço para computador, cor branca, design moderno.'),
('Ventilador', 'BrisaForte', 'TurboWind', 'Usado', 'Ventilador de mesa com 3 velocidades, oscilante, ideal para dias quentes.'),
('Mesa de Centro', 'DecorArt', 'Charme 500', 'Semi-novo', 'Mesa de centro de vidro temperado, estrutura metálica, design elegante.'),
('Fritadeira Elétrica', 'CulináriaMaster', 'AirFry 1800', 'Novo', 'Fritadeira elétrica sem óleo, capacidade de 3,5 litros, timer e temperatura ajustável.'),
('Colchão de Solteiro', 'DormeBem', 'SolteiroConfort', 'Novo', 'Colchão de solteiro ortopédico, espuma D33, antiácaro e antialérgico.'),
('Liquidificador', 'BateBem', 'PowerMix 1000', 'Semi-novo', 'Liquidificador com jarra de vidro, potência de 1000W, diversas velocidades.'),
('Cadeira de Escritório', 'ErgoConfort', 'OfficePro', 'Usado', 'Cadeira de escritório ergonômica, com ajuste de altura e apoio lombar.'),
('Panela Elétrica de Arroz', 'CozinhaPrática', 'RiceCook 5L', 'Novo', 'Panela elétrica de arroz com capacidade para 5 litros, revestimento antiaderente.');

-- adicionando itens na tabela assistencia_tecnica
INSERT INTO assistencia_tecnica (Nome_Tecnico, Especialidade, Disponibilidade, Contato, Descricao, Avaliacao) VALUES 
('Pedro Santos', 'Refrigeradores', '2024-06-04 08:00:00', '(11) 98765-4321', 'Especializado em reparo de refrigeradores de todas as marcas.', 5),
('Ana Oliveira', 'Máquinas de Lavar', '2024-06-05 10:00:00', '(11) 98765-4322', 'Técnica certificada para conserto de máquinas de lavar roupas.', 4),
('Roberto Silva', 'Ar-condicionado', '2024-06-06 09:00:00', '(11) 98765-4323', 'Profissional capacitado para manutenção de sistemas de ar-condicionado.', 4),
('Mariana Costa', 'Telefones Fixos', '2024-06-07 11:00:00', '(11) 98765-4324', 'Especialista em reparos de telefones fixos e sistemas de comunicação.', 5),
('Ricardo Almeida', 'Televisores', '2024-06-08 08:00:00', '(11) 98765-4325', 'Técnico experiente em conserto de televisores de todas as marcas.', 4),
('Carla Santos', 'Notebooks', '2024-06-09 09:00:00', '(11) 98765-4326', 'Especializada em reparo de notebooks e computadores portáteis.', 5),
('Paulo Oliveira', 'Tablets', '2024-06-10 10:00:00', '(11) 98765-4327', 'Técnico capacitado para manutenção e reparo de tablets e dispositivos móveis.', 4),
('Sandra Silva', 'Câmeras Digitais', '2024-06-11 11:00:00', '(11) 98765-4328', 'Profissional especializada em conserto de câmeras digitais e equipamentos fotográficos.', 4),
('Bruno Costa', 'Impressoras', '2024-06-12 08:00:00', '(11) 98765-4329', 'Especialista em reparos de impressoras de todos os modelos e marcas.', 5),
('Fernanda Oliveira', 'Videogames', '2024-06-13 09:00:00', '(11) 98765-4330', 'Técnica certificada para conserto de consoles de videogame e acessórios.', 4),
('Rodrigo Santos', 'Equipamentos de Áudio', '2024-06-14 10:00:00', '(11) 98765-4331', 'Profissional capacitado para manutenção de equipamentos de áudio e som.', 5),
('Tatiane Silva', 'Smartwatches', '2024-06-15 11:00:00', '(11) 98765-4332', 'Especialista em reparos de smartwatches e dispositivos vestíveis.', 4),
('Lucas Costa', 'Fones de Ouvido', '2024-06-16 08:00:00', '(11) 98765-4333', 'Técnico experiente em conserto de fones de ouvido e acessórios de áudio.', 4),
('Marta Oliveira', 'GPS', '2024-06-17 09:00:00', '(11) 98765-4334', 'Profissional especializada em reparos de sistemas de GPS e navegação.', 5),
('Diego Silva', 'Monitores', '2024-06-18 10:00:00', '(11) 98765-4335', 'Especialista em manutenção e reparo de monitores de computador.', 4),
('Juliana Costa', 'Câmeras de Segurança', '2024-06-19 11:00:00', '(11) 98765-4336', 'Técnica certificada para conserto de câmeras de segurança e sistemas de monitoramento.', 4),
('Gustavo Oliveira', 'Projetores', '2024-06-20 08:00:00', '(11) 98765-4337', 'Profissional capacitado para manutenção de projetores e sistemas de projeção.', 5),
('Camila Silva', 'Roteadores', '2024-06-21 09:00:00', '(11) 98765-4338', 'Especialista em reparos de roteadores e dispositivos de rede.', 4),
('Marcelo Costa', 'Modems', '2024-06-22 10:00:00', '(11) 98765-4339', 'Técnico experiente em conserto de modems e equipamentos de internet.', 5),
('Patrícia Oliveira', 'Câmeras Fotográficas', '2024-06-23 11:00:00', '(11) 98765-4340', 'Profissional especializada em reparos de câmeras fotográficas e equipamentos profissionais.', 4),
('Fábio Silva', 'Drone', '2024-06-24 08:00:00', '(11) 98765-4341', 'Especialista em manutenção e reparo de drones e equipamentos de voo.', 5),
('Cristiane Costa', 'Smart TVs', '2024-06-25 09:00:00', '(11) 98765-4342', 'Técnica certificada para conserto de smart TVs e televisores inteligentes.', 4),
('Marcela Oliveira', 'Eletroportáteis', '2024-06-26 10:00:00', '(11) 98765-4343', 'Profissional capacitada para manutenção de eletroportáteis diversos.', 5),
('Rafael Silva', 'Robôs de Limpeza', '2024-06-27 11:00:00', '(11) 98765-4344', 'Especialista em reparos de robôs de limpeza e aspiradores automáticos.', 4),
('Tatiana Costa', 'Relógios Inteligentes', '2024-06-28 08:00:00', '(11) 98765-4345', 'Técnica experiente em conserto de relógios inteligentes e dispositivos vestíveis.', 5),
('Rafaela Oliveira', 'Dispositivos IoT', '2024-06-29 09:00:00', '(11) 98765-4346', 'Profissional especializada em manutenção de dispositivos IoT e automação residencial.', 4),
('Vinícius Silva', 'Aparelhos Médicos', '2024-06-30 10:00:00', '(11) 98765-4347', 'Especialista em reparos de aparelhos médicos e equipamentos hospitalares.', 5),
('Aline Costa', 'Equipamentos de Laboratório', '2024-07-01 11:00:00', '(11) 98765-4348', 'Técnica certificada para conserto de equipamentos de laboratório e análises.', 4),
('Robson Oliveira', 'Instrumentos Musicais', '2024-07-02 08:00:00', '(11) 98765-4349', 'Profissional capacitado para manutenção de instrumentos musicais e equipamentos de áudio.', 5),
('Jéssica Silva', 'Brinquedos Eletrônicos', '2024-07-03 09:00:00', '(11) 98765-4350', 'Especialista em reparos de brinquedos eletrônicos e dispositivos infantis.', 4);

-- adicionado itens na tabela materiais_de_limpeza
INSERT INTO materiais_de_limpeza (Nome_item, Quantidade, Data_recebimento, Data_validade, Categoria, Instrucoes_uso) VALUES 
('Detergente', 50, '2024-06-01', '2024-12-01', 'Limpeza Geral', 'Aplicar o detergente na superfície suja e esfregar com uma esponja úmida.'),
('Água Sanitária', 30, '2024-05-15', '2025-05-15', 'Desinfetantes', 'Diluir a água sanitária em água e aplicar na superfície a ser desinfetada, deixando agir por alguns minutos antes de enxaguar.'),
('Desinfetante', 40, '2024-05-20', '2024-11-20', 'Desinfetantes', 'Aplicar o desinfetante diretamente na superfície e deixar secar naturalmente.'),
('Sabão em Pó', 60, '2024-06-05', '2025-06-05', 'Limpeza de Roupas', 'Adicionar uma medida de sabão em pó na máquina de lavar junto com as roupas.'),
('Lustra-móveis', 25, '2024-06-10', '2025-06-10', 'Limpeza de Móveis', 'Aplicar uma pequena quantidade de lustra-móveis em um pano macio e limpo e espalhar sobre a superfície a ser limpa, em movimentos circulares.'),
('Limpa-vidros', 35, '2024-06-15', '2025-06-15', 'Limpeza de Vidros', 'Aplicar o limpa-vidros em um pano limpo e seco e passar sobre a superfície de vidro, depois polir com um pano seco.'),
('Amaciante de Roupas', 40, '2024-06-20', '2025-06-20', 'Limpeza de Roupas', 'Adicionar uma medida de amaciante na última etapa da lavagem de roupas na máquina.'),
('Alvejante sem Cloro', 30, '2024-06-25', '2025-06-25', 'Desinfetantes', 'Diluir o alvejante sem cloro em água e aplicar na superfície a ser desinfetada, deixando agir por alguns minutos antes de enxaguar.'),
('Esponja de Limpeza', 70, '2024-07-01', '2025-07-01', 'Acessórios de Limpeza', 'Utilizar a esponja de limpeza úmida para esfregar superfícies sujas e encardidas.'),
('Pano de Limpeza', 80, '2024-07-05', '2025-07-05', 'Acessórios de Limpeza', 'Utilizar o pano de limpeza seco para remover poeira e o úmido para limpar superfícies.'),
('Desengordurante', 25, '2024-07-10', '2024-12-10', 'Limpeza Geral', 'Aplicar o desengordurante diretamente na superfície engordurada e esfregar com uma esponja úmida.'),
('Desinfetante de Superfície', 30, '2024-07-15', '2024-12-15', 'Desinfetantes', 'Aplicar o desinfetante diretamente na superfície a ser desinfetada e deixar agir por alguns minutos antes de enxaguar.'),
('Sabonete Líquido', 50, '2024-07-20', '2025-07-20', 'Higiene Pessoal', 'Aplicar o sabonete líquido nas mãos úmidas, espalhar e enxaguar com água.'),
('Removedor de Manchas', 35, '2024-07-25', '2025-07-25', 'Limpeza de Roupas', 'Aplicar o removedor de manchas diretamente sobre a mancha e deixar agir por alguns minutos antes de lavar.'),
('Água Sanitária Perfumada', 30, '2024-08-01', '2025-08-01', 'Desinfetantes', 'Diluir a água sanitária perfumada em água e aplicar na superfície a ser desinfetada, deixando agir por alguns minutos antes de enxaguar.'),
('Desodorizador de Ambiente', 40, '2024-08-05', '2025-08-05', 'Aromatizantes', 'Borrifar o desodorizador de ambiente em áreas a serem aromatizadas, evitando contato com os olhos e inalação direta.'),
('Limpa-pisos', 60, '2024-08-10', '2025-08-10', 'Limpeza de Pisos', 'Aplicar o limpa-pisos diretamente no chão e esfregar com uma vassoura ou mop úmido.'),
('Limpa-carpetes', 25, '2024-08-15', '2025-08-15', 'Limpeza de Carpetes', 'Aplicar o limpa-carpetes na área a ser limpa e esfregar com uma escova ou esponja úmida, depois aspirar o excesso.'),
('Álcool em Gel', 50, '2024-08-20', '2025-08-20', 'Desinfetantes', 'Aplicar o álcool em gel nas mãos e esfregar até secar completamente, sem enxágue.'),
('Desinfetante Multiuso', 35, '2024-08-25', '2025-08-25', 'Desinfetantes', 'Aplicar o desinfetante multiuso diretamente na superfície e deixar secar naturalmente.'),
('Sabão Líquido', 40, '2024-09-01', '2025-09-01', 'Limpeza de Roupas', 'Adicionar uma medida de sabão líquido na máquina de lavar junto com as roupas.'),
('Limpa-fornos', 30, '2024-09-05', '2025-09-05', 'Limpeza de Cozinha', 'Aplicar o limpa-fornos na superfície interna do forno e deixar agir por alguns minutos antes de esfregar com uma esponja úmida.'),
('Amaciante de Carpetes', 25, '2024-09-10', '2025-09-10', 'Limpeza de Carpetes', 'Aplicar o amaciante de carpetes na área a ser limpa e esfregar com uma escova ou esponja úmida, depois enxaguar com água.'),
('Limpa-telas', 40, '2024-09-15', '2025-09-15', 'Limpeza de Eletrônicos', 'Aplicar o limpa-telas em um pano macio e limpo e passar sobre a tela do dispositivo eletrônico, evitando borrifar diretamente no aparelho.'),
('Limpador de Box', 30, '2024-09-20', '2025-09-20', 'Limpeza de Banheiro', 'Aplicar o limpador de box na superfície do box do banheiro e esfregar com uma esponja úmida, depois enxaguar com água.'),
('Desinfetante Hospitalar', 25, '2024-09-25', '2025-09-25', 'Desinfetantes', 'Aplicar o desinfetante hospitalar diretamente na superfície e deixar agir por alguns minutos antes de enxaguar.'),
('Cera para Pisos', 30, '2024-10-01', '2025-10-01', 'Limpeza de Pisos', 'Aplicar a cera para pisos com um aplicador específico e espalhar uniformemente, deixando secar antes de polir.'),
('Detergente Líquido', 40, '2024-10-05', '2025-10-05', 'Limpeza Geral', 'Aplicar o detergente líquido na esponja úmida e esfregar nas superfícies sujas, enxaguando com água.'),
('Desinfetante Odorizador', 30, '2024-10-10', '2025-10-10', 'Desinfetantes', 'Aplicar o desinfetante odorizador diretamente na superfície e deixar agir por alguns minutos antes de enxaguar.'),
('Água Sanitária Perfumada', 25, '2024-10-15', '2025-10-15', 'Desinfetantes', 'Diluir a água sanitária perfumada em água e aplicar na superfície a ser desinfetada, deixando agir por alguns minutos antes de enxaguar.'),
('Limpa-alumínio', 40, '2024-10-20', '2025-10-20', 'Limpeza de Utensílios', 'Aplicar o limpa-alumínio na superfície a ser limpa e esfregar com uma esponja úmida, depois enxaguar com água.'),
('Neutralizador de Odores', 30, '2024-10-25', '2025-10-25', 'Aromatizantes', 'Aplicar o neutralizador de odores em áreas com mau cheiro e deixar agir para eliminar os odores indesejados.');

-- adicionando itens na tabela farmaceuticos
INSERT INTO Farmaceuticos (Nome_Comercial, Tipo, Data_de_Validade, Quantidade_em_Estoque, Instrucoes_de_Uso, Nivel_de_Restricao, Fabricante, Composicao, Efeitos_Colaterais) VALUES
('Paracetamol', 'Medicamento', '2025-05-01', 1500.00, 'Tomar 1 comprimido a cada 6 horas, não exceder 4 comprimidos por dia.', 'Venda Livre', 'GenéricoPharma', 'Paracetamol 500mg', 'Raros efeitos colaterais, como reações alérgicas.'),
('Vitamina C', 'Suplemento', '2023-09-15', 500.00, 'Tomar 1 comprimido por dia, de preferência pela manhã.', 'Venda Livre', 'VitaLife', 'Ácido ascórbico 500mg', 'Pode causar desconforto estomacal em doses elevadas.'),
('Rivotril', 'Medicamento', '2024-12-10', 200.00, 'Tomar 1 comprimido antes de dormir, sob prescrição médica.', 'Prescrição Necessária', 'Roche', 'Clonazepam 2mg', 'Pode causar sonolência e dependência.'),
('Omega-3', 'Suplemento', '2023-11-30', 300.00, 'Tomar 1 cápsula por dia, de preferência durante as refeições.', 'Venda Livre', 'NutriVida', 'Óleo de peixe 1000mg', 'Pode causar sabor residual de peixe e refluxo.'),
('Arnica Montana', 'Homeopático', '2023-07-20', 100.00, 'Dissolver 5 glóbulos em 100ml de água e tomar 1 colher de sopa 3 vezes ao dia.', 'Venda Livre', 'Weleda', 'Arnica Montana 30CH', 'Geralmente bem tolerado, mas pode causar reações alérgicas em algumas pessoas.'),
('Dipirona Sódica', 'Medicamento', '2024-10-05', 800.00, 'Tomar 1 comprimido a cada 8 horas, não exceder 4 comprimidos por dia.', 'Venda Livre', 'NeoQuímica', 'Dipirona Sódica 500mg', 'Pode causar reações alérgicas e queda de pressão arterial.'),
('Probiótico', 'Suplemento', '2023-08-25', 400.00, 'Tomar 1 cápsula por dia, de preferência pela manhã.', 'Venda Livre', 'ProbiLife', 'Lactobacillus acidophilus 1 bilhão UFC', 'Pode causar desconforto abdominal temporário.'),
('Fluoxetina', 'Medicamento', '2024-09-12', 300.00, 'Tomar 1 comprimido pela manhã, sob prescrição médica.', 'Prescrição Necessária', 'EMS', 'Fluoxetina 20mg', 'Pode causar insônia, nervosismo e alterações de apetite.'),
('Sibutramina', 'Medicamento', '2024-11-30', 150.00, 'Tomar 1 cápsula antes do café da manhã, sob prescrição médica.', 'Prescrição Necessária', 'Aché', 'Cloridrato de sibutramina 15mg', 'Pode causar aumento da pressão arterial e taquicardia.'),
('Cloreto de Magnésio', 'Suplemento', '2023-10-10', 600.00, 'Dissolver 1 colher de chá em 200ml de água e tomar 1 vez ao dia.', 'Venda Livre', 'Farmácia de Manipulação', 'Cloreto de Magnésio 33,3%', 'Pode causar diarreia em doses elevadas.'),
('Ibuprofeno', 'Medicamento', '2025-03-15', 1000.00, 'Tomar 1 comprimido a cada 6 horas, não exceder 4 comprimidos por dia.', 'Venda Livre', 'Bayer', 'Ibuprofeno 600mg', 'Pode causar irritação gástrica e aumento da pressão arterial.'),
('Ferro quelato', 'Suplemento', '2023-12-20', 400.00, 'Tomar 1 comprimido por dia, de preferência com o estômago vazio.', 'Venda Livre', 'NatureVida', 'Ferro quelato 40mg', 'Pode causar constipação e escurecimento das fezes.'),
('Ranitidina', 'Medicamento', '2024-08-08', 700.00, 'Tomar 1 comprimido antes do café da manhã e 1 antes do jantar, sob prescrição médica.', 'Prescrição Necessária', 'GenéricoPharma', 'Ranitidina 150mg', 'Pode causar sonolência e dor de cabeça.'),
('Melatonina', 'Suplemento', '2023-06-25', 200.00, 'Tomar 1 cápsula 30 minutos antes de dormir.', 'Venda Livre', 'MelatoninCorp', 'Melatonina 5mg', 'Pode causar sonolência excessiva pela manhã.'),
('Dexametasona', 'Medicamento', '2024-07-10', 300.00, 'Tomar 1 comprimido pela manhã, sob prescrição médica.', 'Prescrição Necessária', 'Biolab', 'Dexametasona 4mg', 'Pode causar aumento de peso e retenção de líquidos.'),
('Calcitriol', 'Suplemento', '2023-05-20', 500.00, 'Tomar 1 cápsula por dia, de preferência com uma refeição.', 'Venda Livre', 'VitaVit', 'Calcitriol 0,25mcg', 'Pode causar hipercalcemia em doses elevadas.'),
('Salbutamol', 'Medicamento', '2025-01-15', 400.00, 'Inalar 1 dose a cada 4-6 horas, conforme necessário.', 'Prescrição Necessária', 'Teuto', 'Salbutamol 100mcg/dose', 'Pode causar tremores e taquicardia.'),
('Multivitamínico', 'Suplemento', '2023-04-30', 600.00, 'Tomar 1 comprimido por dia, de preferência durante as refeições.', 'Venda Livre', 'VitaPlus', 'Vitaminas A, C, D, E, complexo B', 'Pode causar coloração amarela na urina devido à vitamina B2.'),
('Metformina', 'Medicamento', '2024-06-20', 800.00, 'Tomar 1 comprimido 2 vezes ao dia, junto com as refeições.', 'Prescrição Necessária', 'Merck', 'Metformina 850mg', 'Pode causar desconforto abdominal e diarreia.'),
('Colágeno', 'Suplemento', '2023-03-10', 300.00, 'Tomar 1 cápsula por dia, de preferência pela manhã.', 'Venda Livre', 'ColagenCorp', 'Colágeno hidrolisado 500mg', 'Pode causar reações alérgicas em pessoas sensíveis.'),
('Loratadina', 'Medicamento', '2025-02-28', 500.00, 'Tomar 1 comprimido por dia, de preferência pela manhã.', 'Venda Livre', 'EMS', 'Loratadina 10mg', 'Pode causar sonolência e boca seca.'),
('Proteína de Soja', 'Suplemento', '2023-02-15', 200.00, 'Adicionar 1 colher de sopa a sucos, vitaminas ou alimentos.', 'Venda Livre', 'NutriVida', 'Proteína de Soja isolada', 'Pode causar desconforto gastrointestinal em pessoas sensíveis.'),
('Losartana Potássica', 'Medicamento', '2024-05-10', 400.00, 'Tomar 1 comprimido por dia, sob prescrição médica.', 'Prescrição Necessária', 'Biolab', 'Losartana Potássica 50mg', 'Pode causar tontura e tosse seca.'),
('Vitamina D', 'Suplemento', '2023-01-05', 300.00, 'Tomar 1 cápsula por dia, de preferência com uma refeição.', 'Venda Livre', 'VitaLife', 'Vitamina D3 1000UI', 'Pode causar hipervitaminose em doses elevadas.'),
('Ácido Fólico', 'Medicamento', '2025-04-12', 600.00, 'Tomar 1 comprimido por dia, de preferência pela manhã.', 'Venda Livre', 'Teuto', 'Ácido Fólico 5mg', 'Pode causar reações alérgicas em algumas pessoas.'),
('Ômega-6', 'Suplemento', '2023-12-05', 200.00, 'Tomar 1 cápsula por dia, de preferência durante as refeições.', 'Venda Livre', 'NutriVida', 'Óleo de borragem 500mg', 'Pode causar aumento do colesterol LDL em doses elevadas.'),
('Cloridrato de Sertralina', 'Medicamento', '2024-04-30', 700.00, 'Tomar 1 comprimido pela manhã, sob prescrição médica.', 'Prescrição Necessária', 'Eurofarma', 'Cloridrato de Sertralina 50mg', 'Pode causar insônia e aumento de peso.'),
('Creatina', 'Suplemento', '2023-11-15', 300.00, 'Tomar 1 colher de chá (5g) com água ou suco após o treino.', 'Venda Livre', 'NutriPower', 'Creatina monoidratada', 'Pode causar desconforto gastrointestinal em doses elevadas.'),
('Bromazepam', 'Medicamento', '2024-03-20', 200.00, 'Tomar 1 comprimido antes de dormir, sob prescrição médica.', 'Prescrição Necessária', 'EMS', 'Bromazepam 6mg', 'Pode causar sonolência e confusão mental.');

-- adicionando itens na tabela roupas
INSERT INTO Roupas (Nome_da_peca, Quantidade, Categoria, Estado_de_conservacao, Etiqueta, Tecidos, Cor_da_peca, Genero) VALUES
('Camiseta Básica', 200, 'Camiseta', 'Novo', 'M', 'Algodão', 'Branco', 'UNISEX'),
('Calça Jeans Skinny', 150, 'Calça Jeans', 'Semi-novo', 'M', 'Jeans', 'Azul', 'UNISEX'),
('Vestido Floral', 80, 'Vestido', 'Novo', 'P', 'Viscose', 'Floral', 'FEMININO'),
('Camisa Polo', 120, 'Camisa', 'Usado', 'G', 'Poliéster', 'Vermelho', 'MASCULINO'),
('Blusa de Moletom', 100, 'Moletom', 'Semi-novo', 'GG', 'Algodão', 'Cinza', 'UNISEX'),
('Blazer Clássico', 50, 'Blazer', 'Novo', 'M', 'Tecido Sintético', 'Preto', 'UNISEX'),
('Shorts Jeans', 180, 'Shorts', 'Usado', 'P', 'Jeans', 'Azul', 'FEMININO'),
('Casaco de Inverno', 70, 'Casaco', 'Novo', 'G', 'Lã', 'Marrom', 'UNISEX'),
('Camiseta Estampada', 220, 'Camiseta', 'Novo', 'G', 'Algodão', 'Estampado', 'UNISEX'),
('Calça Legging', 130, 'Calça', 'Semi-novo', 'M', 'Poliamida', 'Preto', 'FEMININO'),
('Camisa Social', 90, 'Camisa', 'Usado', 'GG', 'Algodão', 'Branco', 'MASCULINO'),
('Saia Midi', 60, 'Saia', 'Novo', 'P', 'Tecido Plano', 'Verde', 'FEMININO'),
('Jaqueta de Couro', 40, 'Jaqueta', 'Semi-novo', 'M', 'Couro Sintético', 'Preto', 'UNISEX'),
('Top Cropped', 150, 'Top', 'Novo', 'P', 'Poliamida', 'Preto', 'FEMININO'),
('Camiseta Manga Longa', 180, 'Camiseta', 'Usado', 'M', 'Algodão', 'Azul', 'UNISEX'),
('Calça Social', 80, 'Calça', 'Novo', 'G', 'Lã', 'Cinza', 'UNISEX'),
('Macacão Jeans', 70, 'Macacão', 'Semi-novo', 'GG', 'Jeans', 'Azul', 'FEMININO'),
('Suéter de Tricô', 100, 'Suéter', 'Novo', 'M', 'Lã', 'Vermelho', 'UNISEX'),
('Vestido de Festa', 50, 'Vestido', 'Semi-novo', 'P', 'Renda', 'Preto', 'FEMININO'),
('Camisa Xadrez', 120, 'Camisa', 'Novo', 'GG', 'Algodão', 'Xadrez', 'MASCULINO'),
('Shorts de Praia', 90, 'Shorts', 'Usado', 'G', 'Poliamida', 'Estampado', 'UNISEX'),
('Jaqueta Corta-Vento', 60, 'Jaqueta', 'Novo', 'M', 'Nylon', 'Azul', 'UNISEX'),
('Regata Básica', 200, 'Regata', 'Semi-novo', 'GG', 'Algodão', 'Branco', 'UNISEX'),
('Blusa de Tricô', 130, 'Blusa', 'Novo', 'P', 'Lã', 'Rosa', 'FEMININO'),
('Bermuda Cargo', 110, 'Bermuda', 'Usado', 'M', 'Tecido Plano', 'Bege', 'UNISEX'),
('Vestido Jeans', 80, 'Vestido', 'Semi-novo', 'M', 'Jeans', 'Azul', 'FEMININO'),
('Blusa de Cetim', 100, 'Blusa', 'Novo', 'G', 'Cetim', 'Azul', 'FEMININO'),
('Camiseta Estampada', 220, 'Camiseta', 'Semi-novo', 'M', 'Algodão', 'Estampado', 'UNISEX'),
('Calça Pantalona', 70, 'Calça', 'Novo', 'G', 'Viscose', 'Preto', 'FEMININO'),
('Camiseta Polo', 120, 'Camiseta', 'Novo', 'G', 'Algodão', 'Azul', 'MASCULINO'),
('Vestido Longo', 80, 'Vestido', 'Semi-novo', 'P', 'Poliéster', 'Vermelho', 'FEMININO'),
('Jaqueta Bomber', 50, 'Jaqueta', 'Novo', 'M', 'Nylon', 'Preto', 'UNISEX'),
('Shorts de Tecido', 180, 'Shorts', 'Usado', 'P', 'Tecido Plano', 'Verde', 'FEMININO'),
('Blusa de Tricô', 100, 'Blusa', 'Novo', 'M', 'Lã', 'Azul', 'FEMININO'),
('Camisa Social', 90, 'Camisa', 'Semi-novo', 'GG', 'Algodão', 'Branco', 'MASCULINO'),
('Calça Legging', 130, 'Calça', 'Novo', 'M', 'Poliamida', 'Preto', 'FEMININO'),
('Casaco de Lã', 70, 'Casaco', 'Novo', 'G', 'Lã', 'Cinza', 'UNISEX'),
('Top Cropped', 150, 'Top', 'Semi-novo', 'P', 'Poliéster', 'Preto', 'FEMININO'),
('Blusa de Moletom', 100, 'Moletom', 'Novo', 'GG', 'Algodão', 'Azul', 'UNISEX'),
('Saia Midi', 60, 'Saia', 'Semi-novo', 'P', 'Tecido Plano', 'Rosa', 'FEMININO'),
('Blazer de Linho', 40, 'Blazer', 'Usado', 'M', 'Linho', 'Bege', 'UNISEX'),
('Regata Básica', 200, 'Regata', 'Novo', 'GG', 'Algodão', 'Branco', 'UNISEX'),
('Camisa Jeans', 120, 'Camisa', 'Semi-novo', 'M', 'Jeans', 'Azul', 'UNISEX'),
('Shorts Jeans', 180, 'Shorts', 'Novo', 'P', 'Jeans', 'Azul', 'FEMININO'),
('Vestido de Verão', 70, 'Vestido', 'Usado', 'G', 'Algodão', 'Amarelo', 'FEMININO'),
('Blusa Estampada', 130, 'Blusa', 'Semi-novo', 'M', 'Viscose', 'Estampado', 'FEMININO'),
('Calça Cargo', 110, 'Calça', 'Novo', 'M', 'Tecido Plano', 'Verde', 'UNISEX'),
('Sobretudo', 50, 'Casaco', 'Semi-novo', 'GG', 'Lã', 'Preto', 'UNISEX'),
('Body Feminino', 120, 'Body', 'Novo', 'P', 'Poliéster', 'Preto', 'FEMININO'),
('Jaqueta Jeans', 90, 'Jaqueta', 'Semi-novo', 'G', 'Jeans', 'Azul', 'UNISEX'),
('Pijama Feminino', 80, 'Pijama', 'Novo', 'P', 'Algodão', 'Estampado', 'FEMININO'),
('Camiseta Estampada', 220, 'Camiseta', 'Novo', 'G', 'Algodão', 'Estampado', 'UNISEX'),
('Calça Pantacourt', 70, 'Calça', 'Semi-novo', 'M', 'Viscose', 'Preto', 'FEMININO'),
('Blusa Manga Longa', 90, 'Blusa', 'Novo', 'G', 'Viscose', 'Vermelho', 'FEMININO'),
('Vestido Jeans', 80, 'Vestido', 'Novo', 'M', 'Jeans', 'Azul', 'FEMININO'),
('Casaco de Inverno', 60, 'Casaco', 'Usado', 'GG', 'Lã', 'Cinza', 'UNISEX'),
('Polo Manga Curta', 120, 'Polo', 'Semi-novo', 'M', 'Algodão', 'Azul', 'MASCULINO'),
('Shorts de Praia', 90, 'Shorts', 'Novo', 'G', 'Poliamida', 'Estampado', 'UNISEX'),
('Saia Lápis', 80, 'Saia', 'Semi-novo', 'P', 'Tecido Plano', 'Preto', 'FEMININO');

-- adicionando itens na tabela materiais_de_construcao
INSERT INTO materiais_de_construcao(Quantidade, Peso, Material, Descricao) VALUES
(150, 25.5, 'Tijolo Cerâmico', 'Tijolos cerâmicos vermelhos, tamanho padrão para construção de paredes.'),
(200, 15.0, 'Cimento Portland', 'Saco de cimento Portland com alta resistência inicial, ideal para obras estruturais.'),
(100, 30.2, 'Bloco de Concreto', 'Bloco de concreto estrutural, utilizado na construção de paredes e muros.'),
(80, 18.8, 'Telha de Cerâmica', 'Telha de cerâmica esmaltada, cor vermelha, utilizada para cobertura de telhados.'),
(120, 12.5, 'Arame Farpado', 'Rolo de arame farpado galvanizado, utilizado para cercamento de áreas.'),
(90, 40.0, 'Vigota de Madeira', 'Vigota de madeira tratada, dimensões padrão para estruturas de telhado.'),
(250, 8.5, 'Tinta Látex', 'Lata de tinta látex acrílica, cor branca, para pintura interna e externa.'),
(180, 11.0, 'Areia Lavada', 'Metro cúbico de areia lavada, utilizada como componente de argamassas e concretos.'),
(300, 22.3, 'Ferro de Construção', 'Barra de ferro de construção, utilizado em estruturas de concreto armado.'),
(70, 35.0, 'Placa de Gesso', 'Placa de gesso acartonado, para divisórias e forros em construções.'),
(150, 9.8, 'Tinta Esmalte', 'Lata de tinta esmalte sintético, cor verde, para pintura de estruturas metálicas.'),
(120, 28.0, 'Madeira de Pinus', 'Prancha de madeira de pinus tratada, utilizada em estruturas e acabamentos.'),
(200, 14.5, 'Argamassa Pronta', 'Saco de argamassa pronta para assentamento de tijolos e blocos.'),
(100, 32.0, 'Telha de Fibrocimento', 'Telha de fibrocimento ondulada, resistente e de fácil instalação.'),
(80, 19.6, 'Tubo PVC', 'Tubo de PVC soldável, diâmetro padrão para sistemas hidráulicos.'),
(150, 10.2, 'Massa Corrida', 'Balde de massa corrida para nivelamento e correção de imperfeições em paredes.'),
(90, 38.0, 'Prego Comum', 'Pacote de pregos comuns, tamanho 17x21, para fixação de estruturas de madeira.'),
(200, 13.7, 'Silicone Vedante', 'Tubo de silicone vedante, cor branca, para vedação e acabamento em diversos materiais.'),
(120, 25.0, 'Tinta Verniz', 'Lata de tinta verniz transparente, para proteção e acabamento de madeiras.'),
(180, 8.9, 'Rejunte para Cerâmica', 'Saco de rejunte para cerâmica, cor bege, para acabamento de pisos e azulejos.');

-- adicionando itens na tabela voluntarios
INSERT INTO Voluntarios (Nome_Voluntario, Disponibilidade, Habilidades, Email, Telefone, Descricao)
VALUES 
('Ana Maria Silva', '2024-06-10', 'enfermagem', 'anamaria@gmail.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Tenho experiência como enfermeira em hospitais e clínicas.'),
('Carlos Eduardo', '2024-06-12', 'fisioterapia', 'carlosedu@gmail.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Voluntário em centros de reabilitação com habilidades em fisioterapia.'),
('Fernanda Lopes', '2024-06-15', 'nutrição', 'fernandalopes@hotmail.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Nutricionista com experiência em planejamento alimentar e dietas saudáveis.'),
('Mariana Souza', '2024-06-18', 'farmácia', 'mariana.souza@yahoo.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Experiência em farmácias comunitárias e distribuição de medicamentos.'),
('Lucas Pereira', '2024-06-20', 'psicologia', 'lucas_pereira@gmail.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Psicólogo com habilidades em atendimento terapêutico e suporte emocional.'),
('Gabriel Almeida', '2024-06-22', 'primeiros socorros', 'gabriel.almeida@outlook.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Especialista em primeiros socorros com experiência em emergências.'),
('Juliana Costa', '2024-06-25', 'odontologia', 'julianacosta@petmail.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Voluntária em clínicas odontológicas com experiência em cuidados dentários.'),
('Rafael Oliveira', '2024-06-27', 'biomedicina', 'rafael.oliveira@builder.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Experiência em laboratórios de análises clínicas e pesquisas biomédicas.'),
('Bruna Santos', '2024-06-30', 'saúde pública', 'brunasantos@edu.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Especialista em saúde pública com habilidades em planejamento e execução de campanhas de saúde.'),
('Pedro Fernandes', '2024-07-02', 'atendimento de emergência', 'pedro.fernandes@eventos.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Paramédico com experiência em atendimento de emergências e resgate.'),
('Rita Gomes', '2024-07-04', 'enfermagem pediátrica', 'rita.gomes@pediatria.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Enfermeira pediátrica com experiência em cuidados infantis.'),
('João Santos', '2024-06-10', 'enfermagem', 'joaosantos@gmail.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Enfermeiro com experiência em UTI.'),
('Mariana Oliveira', '2024-06-12', 'fisioterapia', 'mariana.oliveira@gmail.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Fisioterapeuta especializada em reabilitação.'),
('Pedro Alves', '2024-06-15', 'nutrição', 'pedro.alves@hotmail.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Nutricionista com foco em alimentação saudável.'),
('Gabriela Silva', '2024-06-18', 'farmácia', 'gabriela.silva@yahoo.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Farmacêutica com experiência em atenção farmacêutica.'),
('Luiz Costa', '2024-06-20', 'psicologia', 'luiz.costa@gmail.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Psicólogo clínico com prática em terapia cognitivo-comportamental.'),
('Laura Ferreira', '2024-06-22', 'primeiros socorros', 'laura.ferreira@outlook.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Instrutora de primeiros socorros certificada.'),
('José Oliveira', '2024-06-25', 'odontologia', 'jose.oliveira@petmail.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Dentista com experiência em tratamentos dentários.'),
('Mariana Santos', '2024-06-27', 'biomedicina', 'mariana.santos@builder.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Técnica de laboratório com conhecimento em análises clínicas.'),
('Luana Almeida', '2024-06-30', 'saúde pública', 'luana.almeida@edu.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Pesquisadora em saúde pública com habilidades em epidemiologia.'),
('Fernando Sousa', '2024-07-02', 'atendimento de emergência', 'fernando.sousa@eventos.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Bombeiro voluntário com treinamento em resgate.'),
('Catarina Gomes', '2024-07-04', 'enfermagem pediátrica', 'catarina.gomes@pediatria.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Enfermeira pediátrica com experiência em cuidados infantis.'),
('Pedro Henrique', '2024-06-10', 'enfermagem', 'pedrohenrique@gmail.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Enfermeiro com experiência em UTI.'),
('Amanda Lima', '2024-06-12', 'fisioterapia', 'amandalima@gmail.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Fisioterapeuta especializada em reabilitação.'),
('José Carlos', '2024-06-15', 'nutrição', 'josecarlos@hotmail.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Nutricionista com foco em alimentação saudável.'),
('Carla Mendes', '2024-06-18', 'farmácia', 'carlamendes@yahoo.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Farmacêutica com experiência em atenção farmacêutica.'),
('Gustavo Oliveira', '2024-06-20', 'psicologia', 'gustavo.oliveira@gmail.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Psicólogo clínico com prática em terapia cognitivo-comportamental.'),
('Camila Ferreira', '2024-06-22', 'primeiros socorros', 'camilaferreira@outlook.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Instrutora de primeiros socorros certificada.'),
('Paulo Oliveira', '2024-06-25', 'odontologia', 'paulooliveira@petmail.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Dentista com experiência em tratamentos dentários.'),
('Rafaela Santos', '2024-06-27', 'biomedicina', 'rafaela.santos@builder.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Técnica de laboratório com conhecimento em análises clínicas.'),
('Marcos Almeida', '2024-06-30', 'saúde pública', 'marcosalmeida@edu.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Pesquisador em saúde pública com habilidades em epidemiologia.'),
('Lucas Ferreira', '2024-07-02', 'atendimento de emergência', 'lucas.ferreira@eventos.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Bombeiro voluntário com treinamento em resgate.'),
('Camila Gomes', '2024-07-04', 'enfermagem pediátrica', 'camila.gomes@pediatria.com', CONCAT('(', LPAD(FLOOR(RAND() * 1000), 3, '0'), ') ', LPAD(FLOOR(RAND() * 10000), 4, '0'), '-', LPAD(FLOOR(RAND() * 10000), 4, '0')), 'Enfermeira pediátrica com experiência em cuidados infantis.');

-- adicionando itens na tabela equipamentos_de_comunicacao
INSERT INTO equipamentos_de_comunicacao (Tipo_de_equipamento, Marca, Modelo, Data_de_aquisicao, Descricao)
VALUES 
('Telefone Celular', 'Samsung', 'Galaxy S20', '2023-01-15', 'Smartphone com sistema Android e câmera de alta resolução.'),
('Telefone Celular', 'Apple', 'iPhone 12', '2023-02-20', 'iPhone com design elegante, tela OLED e processador potente.'),
('Telefone Fixo', 'Intelbras', 'TC 20', '2023-03-10', 'Telefone fixo com design moderno e fácil de usar.'),
('Telefone Fixo', 'Panasonic', 'KX-TGB110LB', '2023-04-05', 'Telefone sem fio com viva-voz e identificador de chamadas.'),
('Rádio Comunicador', 'Motorola', 'Talkabout T800', '2023-05-12', 'Rádio comunicador com alcance de até 35 milhas e resistente à água.'),
('Rádio Comunicador', 'Baofeng', 'UV-5R', '2023-06-18', 'Rádio dual band com display LCD e lanterna embutida.'),
('Telefone Celular', 'Xiaomi', 'Redmi Note 10', '2023-07-22', 'Smartphone com câmera de 48 MP e bateria de longa duração.'),
('Telefone Fixo', 'Siemens', 'Gigaset A490', '2023-08-30', 'Telefone fixo com agenda para até 100 contatos e identificação de chamadas.'),
('Rádio Comunicador', 'Kenwood', 'TK-3402U16P', '2023-09-05', 'Rádio UHF com 16 canais e função de cancelamento de ruído.'),
('Telefone Celular', 'OnePlus', '8T', '2023-10-10', 'Smartphone com tela AMOLED e carregamento rápido.'),
('Rádio Comunicador', 'Midland', 'GXT1000VP4', '2023-11-20', 'Rádio comunicador com alcance de até 36 milhas em áreas abertas.'),
('Telefone Fixo', 'Alcatel', 'Versatis F230', '2023-12-25', 'Telefone sem fio com display luminoso e viva-voz integrado.'),
('Telefone Celular', 'LG', 'K42', '2023-01-10', 'Smartphone com resistência militar e câmera de 13 MP.'),
('Telefone Celular', 'Google', 'Pixel 4a', '2023-02-08', 'Smartphone com câmera de 12.2 MP e armazenamento ilimitado em alta qualidade com Google Fotos.'),
('Rádio Comunicador', 'Cobra', 'ACXT145', '2023-03-17', 'Rádio comunicador com alcance de até 16 milhas e 22 canais.'),
('Telefone Fixo', 'Philips', 'D1301W/BR', '2023-04-22', 'Telefone sem fio com display iluminado e identificador de chamadas.'),
('Telefone Celular', 'Sony', 'Xperia 10 III', '2023-05-28', 'Smartphone com tela OLED de 6 polegadas e câmera tripla.'),
('Rádio Comunicador', 'Uniden', 'SX327-2CKHS', '2023-06-03', 'Rádio comunicador com alcance de até 32 milhas e resistência à água e poeira.'),
('Telefone Fixo', 'VTech', 'CD1113-BR', '2023-07-15', 'Telefone fixo com visor luminoso e identificação de chamadas.'),
('Telefone Celular', 'Nokia', 'C3', '2023-08-20', 'Smartphone com bateria de longa duração e câmera de 8 MP.'),
('Rádio Comunicador', 'TYT', 'MD-380', '2023-09-25', 'Rádio DMR digital com display LCD e programável por PC.'),
('Telefone Fixo', 'Positivo', 'P70S', '2023-10-30', 'Telefone fixo com design compacto e teclado luminoso.'),
('Telefone Celular', 'Asus', 'Zenfone 8', '2023-11-04', 'Smartphone com processador Snapdragon 888 e tela AMOLED de 120 Hz.'),
('Rádio Comunicador', 'Icom', 'IC-F2000S', '2023-12-10', 'Rádio portátil com resistência à água e poeira e 128 canais.'),
('Telefone Fixo', 'Elgin', 'TCF 3000', '2024-01-18', 'Telefone fixo com visor luminoso e agenda para 50 contatos.'),
('Telefone Celular', 'Realme', '7 Pro', '2024-02-22', 'Smartphone com carregamento SuperDart de 65W e tela Super AMOLED.'),
('Rádio Comunicador', 'Retevis', 'RT22', '2024-03-30', 'Rádio comunicador de bolso com áudio claro e bateria de longa duração.'),
('Telefone Fixo', 'Multilaser', 'Telefone Fixo Chip MS45', '2024-04-05', 'Telefone fixo com entrada para chip SIM e identificador de chamadas.'),
('Telefone Celular', 'Lenovo', 'K13 Note', '2024-05-10', 'Smartphone com processador MediaTek Helio G35 e câmera principal de 13 MP.'),
('Rádio Comunicador', 'Baojie', 'BJ-218', '2024-06-15', 'Rádio móvel dual band VHF/UHF com display LCD e 200 canais.'),
('Telefone Fixo', 'Cisco', 'CP-7811-K9', '2024-07-20', 'Telefone IP com suporte para até 2 linhas e viva-voz full-duplex.'),
('Telefone Celular', 'ZTE', 'Blade V30 Vita', '2024-08-25', 'Smartphone com processador MediaTek Helio P60 e câmera de 13 MP.'),
('Rádio Comunicador', 'Anytone', 'AT-D878UV', '2024-09-28', 'Rádio digital DMR com GPS integrado e capacidade de gravação.'),
('Telefone Fixo', 'CISCO', 'SPA303-G1', '2024-10-30', 'Telefone IP de 3 linhas com alto-falante full-duplex e PoE integrado.'),
('Telefone Celular', 'Motorola', 'Moto E20', '2024-11-02', 'Smartphone com processador MediaTek Helio P22 e câmera principal de 13 MP.'),
('Rádio Comunicador', 'Wouxun', 'KG-UV9D', '2024-12-10', 'Rádio dual band VHF/UHF com função cross-band repeat e 999 canais.'),
('Telefone Fixo', 'Grandstream', 'GXP1610', '2025-01-15', 'Telefone IP de 1 linha com áudio em HD e suporte a PoE.'),
('Telefone Celular', 'Xiaomi', 'Redmi 10', '2025-02-20', 'Smartphone com processador MediaTek Helio G88 e câmera quádrupla de 50 MP.'),
('Rádio Comunicador', 'Alinco', 'DJ-MD5TGP', '2025-03-25', 'Rádio dual band VHF/UHF com GPS integrado e display colorido.'),
('Telefone Fixo', 'Yealink', 'SIP-T21P E2', '2025-04-30', 'Telefone IP de 2 linhas com áudio HD e PoE integrado.'),
('Telefone Celular', 'Oppo', 'A15s', '2025-05-10', 'Smartphone com processador MediaTek Helio P35 e câmera principal de 13 MP.');
